const getRandomNum = require('../util.js');

const options = [
    {name: "Kauri Conifers", url: "https://en.wikipedia.org/wiki/Agathis"},
    {name: "Monkey-puzzle Trees", url: "https://en.wikipedia.org/wiki/Araucaria"},
    {name: "Tasmanian Cedars", url: "https://en.wikipedia.org/wiki/Athrotaxis"},
    {name: "Cypress-pines", url: "https://en.wikipedia.org/wiki/Callitris"},
    {name: "Incense Cedars", url: "https://en.wikipedia.org/wiki/Calocedrus"},
    {name: "False Cypresses", url: "https://en.wikipedia.org/wiki/Chamaecyparis"},
    {name: "Oriental Cedars", url: "https://en.wikipedia.org/wiki/Cryptomeria"},
    {name: "Cunninghamia", url: "https://en.wikipedia.org/wiki/Cunninghamia"},
    {name: "True Cypresses", url: "https://en.wikipedia.org/wiki/Cupressus"},
    {name: "Oriental Swamp Cypresses", url: "https://en.wikipedia.org/wiki/Glyptostrobus"},
    {name: "Juniper Trees", url: "https://en.wikipedia.org/wiki/Juniperus"},
    {name: "Dwarf Redwoodss", url: "https://en.wikipedia.org/wiki/Metasequoia"},
    {name: "True Redwoods", url: "https://en.wikipedia.org/wiki/Sequoia_(genus)"},
    {name: "Sequoiadendrons", url: "https://en.wikipedia.org/wiki/Sequoiadendron"},
    {name: "Taiwania Trees", url: "https://en.wikipedia.org/wiki/Taiwania"},
    {name: "Bald or Swamp Cypresses", url: "https://en.wikipedia.org/wiki/Taxodium"},
    {name: "Arborvitae", url: "https://en.wikipedia.org/wiki/Thuja"},
    {name: "Fir Trees", url: "https://en.wikipedia.org/wiki/Abies"},
    {name: "True Cedars", url: "https://en.wikipedia.org/wiki/Cedrus"},
    {name: "Larches", url: "https://en.wikipedia.org/wiki/Larix"},
    {name: "Spruces", url: "https://en.wikipedia.org/wiki/Picea"},
    {name: "Pines", url: "https://en.wikipedia.org/wiki/Pinus"},
    {name: "Douglas Firs", url: "https://en.wikipedia.org/wiki/Pseudotsuga"},
    {name: "Hemlocks", url: "https://en.wikipedia.org/wiki/Tsuga"},
    {name: "African Podocarps", url: "https://en.wikipedia.org/wiki/Afrocarpus"},
    {name: "Kahikatea", url: "https://en.wikipedia.org/wiki/Dacrycarpus"},
    {name: "Rimu", url: "https://en.wikipedia.org/wiki/Dacrydium"},
    {name: "Australasian Podocarps", url: "https://en.wikipedia.org/wiki/Podocarpus"},
    {name: "Sciadopitys Trees", url: "https://en.wikipedia.org/wiki/Sciadopitys"},
    {name: "Yew Trees", url: "https://en.wikipedia.org/wiki/Taxus"},
    {name: "Torreyas", url: "https://en.wikipedia.org/wiki/Torreya"},
    {name: "Cycadian Trees", url: "https://en.wikipedia.org/wiki/Cycas"},
    {name: "Bread Trees", url: "https://en.wikipedia.org/wiki/Encephalartos"},
    {name: "Ginkgos or Maidenhair Trees", url: "https://en.wikipedia.org/wiki/Ginkgos"},
    {name: "Maples", url: "https://en.wikipedia.org/wiki/Acer_(plant)"},
    {name: "Irdyline Trees", url: "https://en.wikipedia.org/wiki/Cordyline"},
    {name: "Furcraea", url: "https://en.wikipedia.org/wiki/Furcraea"},
    {name: "Nolina Trees", url: "https://en.wikipedia.org/wiki/Nolina"},
    {name: "Yuccas", url: "https://en.wikipedia.org/wiki/Yucca"},
    {name: "Cashews", url: "https://en.wikipedia.org/wiki/Anacardium"},
    {name: "Smoke Trees", url: "https://en.wikipedia.org/wiki/Cotinus"},
    {name: "Harpephyllum Plum Trees", url: "https://en.wikipedia.org/wiki/Harpephyllum"},
    {name: "Mangos", url: "https://en.wikipedia.org/wiki/Mangifera"},
    {name: "Poisonwoods", url: "https://en.wikipedia.org/wiki/Metopium"},
    {name: "Pistachios and Terebinth", url: "https://en.wikipedia.org/wiki/Pistacia"},
    {name: "Sumacs", url: "https://en.wikipedia.org/wiki/Rhus"},
    {name: "Pepper Trees", url: "https://en.wikipedia.org/wiki/Schinus"},
    {name: "Mombins", url: "https://en.wikipedia.org/wiki/Spondias"},
    {name: "Poison Sumacs", url: "https://en.wikipedia.org/wiki/Toxicodendron"},
    {name: "Custard Apples", url: "https://en.wikipedia.org/wiki/Annona"},
    {name: "Pawpaws", url: "https://en.wikipedia.org/wiki/Asimina"},
    {name: "Yellow Oleanders", url: "https://en.wikipedia.org/wiki/Cascabela"},
    {name: "Oleander", url: "https://en.wikipedia.org/wiki/Nerium"},
    {name: "Frangipani Trees", url: "https://en.wikipedia.org/wiki/Plumeria"},
    {name: "Holly Trees", url: "https://en.wikipedia.org/wiki/Ilex"},
    {name: "False Holly Trees", url: "https://en.wikipedia.org/wiki/Nemopanthus"},
    {name: "Aralias", url: "https://en.wikipedia.org/wiki/Aralia"},
    {name: "Brahea Palm Trees", url: "https://en.wikipedia.org/wiki/Brahea"},
    {name: "Date Palms", url: "https://en.wikipedia.org/wiki/Phoenix_(plant)"},
    {name: "Sabal Palms", url: "https://en.wikipedia.org/wiki/Sabal"},
    {name: "Alders", url: "https://en.wikipedia.org/wiki/Alnus"},
    {name: "Birches", url: "https://en.wikipedia.org/wiki/Betula"},
    {name: "Hornbeams", url: "https://en.wikipedia.org/wiki/Carpinus"},
    {name: "Hazels", url: "https://en.wikipedia.org/wiki/Corylus"},
    {name: "Trumpet Trees", url: "https://en.wikipedia.org/wiki/Tabebuia"},
    {name: "Baobab Trees", url: "https://en.wikipedia.org/wiki/Adansonia"},
    {name: "Durians", url: "https://en.wikipedia.org/wiki/Durio"},
    {name: "Box Shrubs", url: "https://en.wikipedia.org/wiki/Buxus"},
    {name: "Hackberries and Sugarberries", url: "https://en.wikipedia.org/wiki/Celtis"},
    {name: "Elders", url: "https://en.wikipedia.org/wiki/Sambucus"},
    {name: "Viburnum and Blackhaws", url: "https://en.wikipedia.org/wiki/Viburnum"},
    {name: "Beefwoods", url: "https://en.wikipedia.org/wiki/Casuarina"},
    {name: "Euonymus Shrubs", url: "https://en.wikipedia.org/wiki/Euonymus"},
    {name: "Maranthes Trees", url: "https://en.wikipedia.org/wiki/Maranthes"},
    {name: "Dogwoods", url: "https://en.wikipedia.org/wiki/Cornus"},
    {name: "Davidson’s Plum Trees", url: "https://en.wikipedia.org/wiki/Davidsonia"},
    {name: "Ebony and Persimmons", url: "https://en.wikipedia.org/wiki/Diospyros"},
    {name: "Elaeagnus trees", url: "https://en.wikipedia.org/wiki/Elaeagnus"},
    {name: "Rhododendron Trees", url: "https://en.wikipedia.org/wiki/Rhododendron"},
    {name: "Spurge Trees", url: "https://en.wikipedia.org/wiki/Euphorbia"},
    {name: "Rubber Trees", url: "https://en.wikipedia.org/wiki/Hevea"},
    {name: "Hippomane Trees", url: "https://en.wikipedia.org/wiki/Hippomane"},
    {name: "Cassava", url: "https://en.wikipedia.org/wiki/Manihot"},
    {name: "Tallow Trees", url: "https://en.wikipedia.org/wiki/Sapium"},
    {name: "Maidenbushes", url: "https://en.wikipedia.org/wiki/Savia_(plant)"},
    {name: "Orchid Trees", url: "https://en.wikipedia.org/wiki/Bauhinia"},
    {name: "Redbuds", url: "https://en.wikipedia.org/wiki/Cercis"},
    {name: "Yellowwoods", url: "https://en.wikipedia.org/wiki/Cladrastis"},
    {name: "True Rosewoods", url: "https://en.wikipedia.org/wiki/Dalbergia"},
    {name: "Poincianas", url: "https://en.wikipedia.org/wiki/Delonix"},
    {name: "Coral Trees", url: "https://en.wikipedia.org/wiki/Erythrina"},
    {name: "Sugarpod Trees", url: "https://en.wikipedia.org/wiki/Inga"},
    {name: "Fishpoison Trees", url: "https://en.wikipedia.org/wiki/Piscidia"},
    {name: "Locusts", url: "https://en.wikipedia.org/wiki/Robinia"},
    {name: "Tamarinds", url: "https://en.wikipedia.org/wiki/Tamarindus"},
    {name: "Chestnuts and Chinkapins", url: "https://en.wikipedia.org/wiki/Castanea_(plant)"},
    {name: "Beeches", url: "https://en.wikipedia.org/wiki/Fagus_(plant)"},
    {name: "Stonefruit Oaks", url: "https://en.wikipedia.org/wiki/Lithocarpus"},
    {name: "Oaks", url: "https://en.wikipedia.org/wiki/Quercus"},
    {name: "Currants and Gooseberries", url: "https://en.wikipedia.org/wiki/Ribes"},
    {name: "Liquidambar Trees", url: "https://en.wikipedia.org/wiki/Liquidambar"},
    {name: "Buckeyes and Horse Chestnuts", url: "https://en.wikipedia.org/wiki/Aesculus"},
    {name: "Anise-Trees", url: "https://en.wikipedia.org/wiki/Illicium"},
    {name: "Hickories and Pecans", url: "https://en.wikipedia.org/wiki/Carya"},
    {name: "Walnuts", url: "https://en.wikipedia.org/wiki/Juglans"},
    {name: "Cinnamon and Camphor", url: "https://en.wikipedia.org/wiki/Cinnamomum"},
    {name: "True Laurels", url: "https://en.wikipedia.org/wiki/Laurus"},
    {name: "Bay Trees", url: "https://en.wikipedia.org/wiki/Persea"},
    {name: "Sassafras Trees", url: "https://en.wikipedia.org/wiki/Sassafras"},
    {name: "Tulip Trees", url: "https://en.wikipedia.org/wiki/Liriodendron"},
    {name: "Magnolias", url: "https://en.wikipedia.org/wiki/Magnolia"},
    {name: "Hibiscus Trees", url: "https://en.wikipedia.org/wiki/Hibiscus"},
    {name: "Fig Trees", url: "https://en.wikipedia.org/wiki/Fig_trees"},
    {name: "Cockspur Thorns", url: "https://en.wikipedia.org/wiki/Maclura"},
    {name: "Mulberries", url: "https://en.wikipedia.org/wiki/Morus_(plant)"},
    {name: "Moringa Trees", url: "https://en.wikipedia.org/wiki/Moringa"},
    {name: "Peppermint Myrtles", url: "https://en.wikipedia.org/wiki/Agonis"},
    {name: "Eucalyptus Trees", url: "https://en.wikipedia.org/wiki/Eucalyptus"},
    {name: "Eugenia Trees", url: "https://en.wikipedia.org/wiki/Eugenia"},
    {name: "Myrtles", url: "https://en.wikipedia.org/wiki/Myrtus"},
    {name: "Guavas", url: "https://en.wikipedia.org/wiki/Psidium"},
    {name: "Rose Myrtles", url: "https://en.wikipedia.org/wiki/Rhodomyrtus"},
    {name: "Lillypillies", url: "https://en.wikipedia.org/wiki/Syzygium"},
    {name: "Water Gum Trees", url: "https://en.wikipedia.org/wiki/Tristaniopsis"},
    {name: "Southern Beeches", url: "https://en.wikipedia.org/wiki/Nothofagus"},
    {name: "Blollies", url: "https://en.wikipedia.org/wiki/Guapira"},
    {name: "Pisonia or Mapou Trees", url: "https://en.wikipedia.org/wiki/Pisonia"},
    {name: "Tupelo Trees", url: "https://en.wikipedia.org/wiki/Nyssa_(plant)"},
    {name: "Fringe Trees", url: "https://en.wikipedia.org/wiki/Chionanthus"},
    {name: "False Privets", url: "https://en.wikipedia.org/wiki/Forestiera"},
    {name: "Ashes", url: "https://en.wikipedia.org/wiki/Fraxinus"},
    {name: "Privets", url: "https://en.wikipedia.org/wiki/Ligustrum"},
    {name: "Olives", url: "https://en.wikipedia.org/wiki/Olea"},
    {name: "Osmanthus Trees", url: "https://en.wikipedia.org/wiki/Osmanthus"},
    {name: "Lilacs", url: "https://en.wikipedia.org/wiki/Syringa"},
    {name: "Averrhoa Trees", url: "https://en.wikipedia.org/wiki/Averrhoa"},
    {name: "Pandanus Trees", url: "https://en.wikipedia.org/wiki/Pandanus"},
    {name: "Gooseberry Trees", url: "https://en.wikipedia.org/wiki/Phyllanthus"},
    {name: "Sycamores", url: "https://en.wikipedia.org/wiki/Platanus"},
    {name: "Giant Clumping Bamboos", url: "https://en.wikipedia.org/wiki/Dendrocalamus"},
    {name: "Coccoloba Trees", url: "https://en.wikipedia.org/wiki/Coccoloba"},
    {name: "Macadamia Nut Trees", url: "https://en.wikipedia.org/wiki/Macadamia"},
    {name: "Geebungs", url: "https://en.wikipedia.org/wiki/Persoonia"},
    {name: "Nakedwoods", url: "https://en.wikipedia.org/wiki/Colubrina"},
    {name: "Buckthorns", url: "https://en.wikipedia.org/wiki/Rhamnus_(plant)"},
    {name: "Ziziphus Trees", url: "https://en.wikipedia.org/wiki/Ziziphus"},
    {name: "True Mangroves", url: "https://en.wikipedia.org/wiki/Rhizophora"},
    {name: "Chokeberries", url: "https://en.wikipedia.org/wiki/Aronia"},
    {name: "Flowering Quinces", url: "https://en.wikipedia.org/wiki/Chaenomeles"},
    {name: "Hawthorns", url: "https://en.wikipedia.org/wiki/Crataegus"},
    {name: "Mediterranean Quince", url: "https://en.wikipedia.org/wiki/Quince"},
    {name: "Apples and Crabapples", url: "https://en.wikipedia.org/wiki/Malus"},
    {name: "Medlars", url: "https://en.wikipedia.org/wiki/Mespilus"},
    {name: "Cherries, Plums, Peaches, Apricots, Almonds and Cherry Laurels", url: "https://en.wikipedia.org/wiki/Prunuss"},
    {name: "Oriental Quinces", url: "https://en.wikipedia.org/wiki/Pseudocydonia"},
    {name: "Firethorns", url: "https://en.wikipedia.org/wiki/Pyracantha"},
    {name: "Pears", url: "https://en.wikipedia.org/wiki/Pyrus"},
    {name: "Mountain Ashes and Rowans", url: "https://en.wikipedia.org/wiki/Sorbus"},
    {name: "Oranges, Lemons, Limes, Grapefruits, and Kumquats", url: "https://en.wikipedia.org/wiki/Citrus"},
    {name: "Poplars, Cottonwoods, and Aspens", url: "https://en.wikipedia.org/wiki/Populus"},
    {name: "Willows", url: "https://en.wikipedia.org/wiki/Salix"},
    {name: "Toadwoods", url: "https://en.wikipedia.org/wiki/Cupania"},
    {name: "Soapberries", url: "https://en.wikipedia.org/wiki/Sapindus"},
    {name: "Bustics", url: "https://en.wikipedia.org/wiki/Dipholis"},
    {name: "Tobacco", url: "https://en.wikipedia.org/wiki/Nicotiana"},
    {name: "Nightshades and Potatoes", url: "https://en.wikipedia.org/wiki/Solanum"},
    {name: "Bladdernuts", url: "https://en.wikipedia.org/wiki/Staphylea"},
    {name: "Bottle Trees", url: "https://en.wikipedia.org/wiki/Brachychiton"},
    {name: "Cola Trees", url: "https://en.wikipedia.org/wiki/Cola_acuminata"},
    {name: "Parasol Trees", url: "https://en.wikipedia.org/wiki/Firmiana"},
    {name: "Cacao Trees", url: "https://en.wikipedia.org/wiki/Theobroma"},
    {name: "Silverbells", url: "https://en.wikipedia.org/wiki/Halesia"},
    {name: "Storaxes and Snowbells", url: "https://en.wikipedia.org/wiki/Styrax"},
    {name: "Basswoods", url: "https://en.wikipedia.org/wiki/Tilia"},
    {name: "Elms", url: "https://en.wikipedia.org/wiki/Ulmus"},
    {name: "Fiddlewoods", url: "https://en.wikipedia.org/wiki/Citharexylum"},
]

module.exports = function trees(msg, args) {
    const index = getRandomNum(options.length);
    msg.channel.send(options[index].name + "!");
    msg.channel.send(options[index].url);
}